---
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  no-await-in-loop: 0
  no-cond-assign: error
  no-console: 0
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-empty: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: 0
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations:
    - error
    - functions
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-prototype-builtins: 0
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: 0
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: 0
  no-unsafe-negation: 0
  use-isnan: error
  valid-jsdoc: 0
  valid-typeof: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: 0
  block-scoped-var: 0
  class-methods-use-this: 0
  complexity:
    - error
    - 20
  consistent-return: 0
  curly: 0
  default-case: 0
  dot-location: 0
  dot-notation: 0
  eqeqeq: error
  guard-for-in: error
  no-alert: 0
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: 0
  no-empty-function: 0
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: 0
  no-fallthrough: error
  no-floating-decimal: 0
  no-global-assign: 0
  no-implicit-coercion: 0
  no-implied-eval: error
  no-invalid-this: 0
  no-iterator: error
  no-labels:
    - error
    - allowLoop: true
      allowSwitch: true
  no-lone-blocks: error
  no-loop-func: error
  no-magic-number: 0
  no-multi-spaces: 0
  no-multi-str: 0
  no-native-reassign: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-octal: error
  no-param-reassign: 0
  no-proto: error
  no-redeclare: error
  no-restricted-properties: 0
  no-return-assign: error
  no-return-await: 0
  no-script-url: error
  no-self-assign: 0
  no-self-compare: error
  no-sequences: 0
  no-throw-literal: 0
  no-unmodified-loop-condition: 0
  no-unused-expressions: error
  no-unused-labels: 0
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: 0
  no-useless-return: 0
  no-void: error
  no-warning-comments: 0
  no-with: error
  prefer-promise-reject-errors: 0
  radix: error
  require-await: 0
  vars-on-top: 0
  wrap-iife: error
  yoda: 0

  # Strict
  strict: 0

  # Variables
  init-declarations: 0
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: 0
  no-shadow-restricted-names: error
  no-shadow: 0
  no-undef-init: error
  no-undef: 0
  no-undefined: 0
  no-unused-vars: 0
  no-use-before-define: 0

  # Node.js and CommonJS
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-mixed-requires: 0
  no-new-require: 0
  no-path-concat: error
  no-process-env: 0
  no-process-exit: error
  no-restricted-modules: 0
  no-sync: 0

  # Stylistic Issues
  array-bracket-spacing: 0
  block-spacing: 0
  brace-style: 0
  camelcase: 0
  capitalized-comments: 0
  comma-dangle:
    - error
    - never
  comma-spacing: 0
  comma-style: 0
  computed-property-spacing: 0
  consistent-this: 0
  eol-last: 0
  func-call-spacing: 0
  func-name-matching: 0
  func-names: 0
  func-style: 0
  id-length: 0
  id-match: 0
  indent: 0
  jsx-quotes: 0
  key-spacing: 0
  keyword-spacing: 0
  line-comment-position: 0
  linebreak-style: 0
  lines-around-comment: 0
  lines-around-directive: 0
  max-depth: 0
  max-len: 0
  max-nested-callbacks: 0
  max-params: 0
  max-statements-per-line: 0
  max-statements:
    - warn
    - 60
  multiline-ternary: 0
  new-cap: 0
  new-parens: 0
  newline-after-var: 0
  newline-before-return: 0
  newline-per-chained-call: 0
  no-array-constructor: 0
  no-bitwise: 0
  no-continue: 0
  no-inline-comments: 0
  no-lonely-if: 0
  no-mixed-operators: 0
  no-mixed-spaces-and-tabs: 0
  no-multi-assign: 0
  no-multiple-empty-lines: 0
  no-negated-condition: 0
  no-nested-ternary: 0
  no-new-object: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-spaced-func: 0
  no-tabs: 0
  no-ternary: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  no-unneeded-ternary: 0
  object-curly-newline: 0
  object-curly-spacing: 0
  object-property-newline: 0
  one-var-declaration-per-line: 0
  one-var: 0
  operator-assignment: 0
  operator-linebreak: 0
  padded-blocks: 0
  quote-props: 0
  quotes: 0
  require-jsdoc: 0
  semi-spacing: 0
  semi: 0
  sort-keys: 0
  sort-vars: 0
  space-before-blocks: 0
  space-before-function-paren: 0
  space-in-parens: 0
  space-infix-ops: 0
  space-unary-ops: 0
  spaced-comment: 0
  template-tag-spacing: 0
  unicode-bom: 0
  wrap-regex: 0

  # ECMAScript 6
  arrow-body-style: 0
  arrow-parens: 0
  arrow-spacing: 0
  constructor-super: 0
  generator-star-spacing: 0
  no-class-assign: 0
  no-confusing-arrow: 0
  no-const-assign: 0
  no-dupe-class-members: 0
  no-duplicate-imports: 0
  no-new-symbol: 0
  no-restricted-imports: 0
  no-this-before-super: 0
  no-useless-computed-key: 0
  no-useless-constructor: 0
  no-useless-rename: 0
  no-var: 0
  object-shorthand: 0
  prefer-arrow-callback: 0
  prefer-const: 0
  prefer-destructuring: 0
  prefer-numeric-literals: 0
  prefer-rest-params: 0
  prefer-reflect: 0
  prefer-spread: 0
  prefer-template: 0
  require-yield: 0
  rest-spread-spacing: 0
  sort-imports: 0
  symbol-description: 0
  template-curly-spacing: 0
  yield-star-spacing: 0
